steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/agent-sandbox-476202/agent-sandbox/sandbox-proxy:latest'
      - '.'

# Push all tags to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/agent-sandbox-476202/agent-sandbox/sandbox-proxy:latest'

# Optional: Set build timeout (default is 10 minutes)
timeout: 600s

# Optional: Specify options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
